#!/usr/bin/env python3
"""Phase A: does the detector over-fire on ANY empty ground, or only on unfamiliar ground?

WHY THIS RUNS BEFORE THE 8-HOUR CONTROL
The paper attributes cross-domain false positives to training-set composition: 98.7 percent of the
VisDrone training tiles contain an object, so the detector was trained almost exclusively on evidence
that something is present. That is a conjecture. Before spending 8 GPU hours retraining to test it,
there is a free question that sharpens the prediction:

    give the model empty tiles from its OWN domain, held out of training, and empty tiles from the
    target domain. Does it fire on both, or only on the unfamiliar one?

  similar FP/tile  -> the propensity was trained in, is not domain-specific, and the composition
                      explanation is supported. The control should work.
  WiSARD far worse -> the effect is dominated by unfamiliar terrain, not by training composition,
                      and the control will probably disappoint.

Evaluating a detector on background-only sets to characterise domain-shift robustness is established
practice and needs no retraining.

THE HELD-OUT SET IS EXACT, NOT APPROXIMATE
`select_tiles` keeps every positive plus `rng.sample(negatives, round(len(negatives)*0.175))` with
`random.Random(42)` constructed fresh per frame, so the selection is deterministic and reproducible.
We replay it per frame and keep the negatives it did NOT choose. Those tiles were generated by the
same pipeline as the training data and then discarded, so they are in-domain and genuinely unseen.

A NOTE ON WHAT THIS REVEALS ABOUT THE ORIGINAL INTENT
select_tiles' docstring says "deliberately retaining ~15-20% negatives is the fix". But the parameter
is a fraction OF THE AVAILABLE NEGATIVES, not a target composition. VisDrone yields only 4,221
negatives against 39,984 positives, so keeping 17.5 percent of them produces a training set that is
1.8 percent negative, not 15-20. The intended fix was never actually applied at the intended
strength.

Writes tiles to a scratch directory; touches nothing under data/processed or configs/.
"""

from __future__ import annotations

import argparse
import csv
import json
import random
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.sar.data.tiling import tile_dataset  # noqa: E402
from src.sar.data.visdrone import visdrone_id_to_rgb_id  # noqa: E402

RAW = ROOT / "data" / "raw" / "VisDrone"
WISARD = Path("sar-drone-data/processed/sar_wisard_tiled")


def read_boxes_px(label_path: Path, w: int, h: int):
    out = []
    if not label_path.exists():
        return out
    for line in label_path.read_text().splitlines():
        t = line.split()
        if len(t) < 5:
            continue
        cid = visdrone_id_to_rgb_id(int(t[0]))
        if cid is None:
            continue
        cx, cy, bw, bh = (float(v) for v in t[1:5])
        out.append((cid, int((cx - bw / 2) * w), int((cy - bh / 2) * h),
                    int((cx + bw / 2) * w), int((cy + bh / 2) * h)))
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-dir", required=True, help="scratch dir for the held-out negative tiles")
    ap.add_argument("--split", default="train")
    ap.add_argument("--neg-frac", type=float, default=0.175, help="must match the original build")
    ap.add_argument("--seed", type=int, default=42)
    cli = ap.parse_args()

    img_dir, lbl_dir = RAW / "images" / cli.split, RAW / "labels" / cli.split
    out = Path(cli.out_dir)
    (out / "images" / "test").mkdir(parents=True, exist_ok=True)
    (out / "labels" / "test").mkdir(parents=True, exist_ok=True)

    n_pos = n_neg = n_kept = n_held = 0
    frames = sorted(img_dir.glob("*.jpg"))
    print(f"replaying the tile selection over {len(frames)} frames...", flush=True)

    for k, ip in enumerate(frames):
        with Image.open(ip) as im:
            w, h = im.size
            boxes = read_boxes_px(lbl_dir / f"{ip.stem}.txt", w, h)
            tiled = tile_dataset(w, h, boxes, tile_size=640, overlap=0.2, min_visible_frac=0.3)
            positives = [(t, l) for t, l in tiled if l]
            negatives = [(t, l) for t, l in tiled if not l]
            n_pos += len(positives)
            n_neg += len(negatives)

            # Exact replay of select_tiles' choice for this frame. random.sample consumes the
            # RNG based only on the population LENGTH, not its contents, so sampling indices with
            # a freshly seeded Random gives the same positions select_tiles picked from the list.
            rng = random.Random(cli.seed)
            keep_n = min(round(len(negatives) * cli.neg_frac), len(negatives))
            kept_idx = set(rng.sample(range(len(negatives)), keep_n)) if negatives else set()
            n_kept += len(kept_idx)

            held = [tn for i, tn in enumerate(negatives) if i not in kept_idx]
            for tile, _ in held:
                tx0, ty0, tx1, ty1 = tile
                name = f"{ip.stem}_n{tx0}_{ty0}"
                im.crop(tile).save(out / "images" / "test" / f"{name}.jpg", quality=95)
                (out / "labels" / "test" / f"{name}.txt").write_text("")
                n_held += 1
        if k % 1500 == 0:
            print(f"  {k}/{len(frames)}  held-out negatives so far {n_held}", flush=True)

    n_wis_neg = sum(1 for p in (WISARD / "labels" / "test").iterdir()
                    if p.suffix == ".txt" and not p.read_text().strip())

    summary = {
        "visdrone_split": cli.split,
        "positive_tiles": n_pos,
        "negative_tiles_total": n_neg,
        "negatives_kept_in_training": n_kept,
        "negatives_held_out": n_held,
        "realised_training_negative_fraction": round(n_kept / (n_pos + n_kept), 5),
        "intended_by_docstring": "0.15-0.20",
        "wisard_negative_tiles": n_wis_neg,
        "wisard_negative_fraction": round(n_wis_neg / 37058, 5),
        "held_out_dir": str(out),
        "note": ("negative_keep_frac is a fraction OF AVAILABLE NEGATIVES, not a target composition. "
                 "VisDrone is object-dense, so 17.5 percent of its negatives yields a training set "
                 "that is under 2 percent negative rather than the 15-20 percent the code intended."),
    }
    (ROOT / "results" / "background_pool.json").write_text(json.dumps(summary, indent=2) + "\n")
    for k_, v in summary.items():
        if not isinstance(v, str) or len(v) < 60:
            print(f"  {k_}: {v}")
    print(f"\n[write] {ROOT/'results'/'background_pool.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
